/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcregstriation;
import javax.swing.*;
import java.awt.*;
import java.util.Scanner;
import java.io.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author root
 */
public class main extends javax.swing.JFrame{

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        mainPanel = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        HeadLable = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnlogout = new javax.swing.JButton();
        navPanel = new javax.swing.JPanel();
        btnin = new javax.swing.JButton();
        btnout = new javax.swing.JButton();
        btnreg = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        formPanel = new javax.swing.JPanel();
        welcomePanel = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        checkinPanel = new javax.swing.JPanel();
        inLable1 = new javax.swing.JLabel();
        inLabel2 = new javax.swing.JLabel();
        inIdp = new javax.swing.JTextField();
        inSer = new javax.swing.JTextField();
        chek_IN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firtName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        checkoutPanel = new javax.swing.JPanel();
        outId = new javax.swing.JLabel();
        outId1 = new javax.swing.JLabel();
        checkout = new javax.swing.JButton();
        outtext2 = new javax.swing.JTextField();
        outserial = new javax.swing.JTextField();
        outtext1 = new javax.swing.JTextField();
        outid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rgisterPane1 = new javax.swing.JPanel();
        reglable10 = new javax.swing.JLabel();
        reglable11 = new javax.swing.JLabel();
        reglable12 = new javax.swing.JLabel();
        reglable13 = new javax.swing.JLabel();
        reglable14 = new javax.swing.JLabel();
        reglable15 = new javax.swing.JLabel();
        reglable16 = new javax.swing.JLabel();
        fnt = new javax.swing.JTextField();
        lnt = new javax.swing.JTextField();
        idt = new javax.swing.JTextField();
        brandt = new javax.swing.JTextField();
        serialt = new javax.swing.JTextField();
        blockt = new javax.swing.JTextField();
        dormt = new javax.swing.JTextField();
        regbtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        reglabel9 = new javax.swing.JLabel();
        pt = new javax.swing.JTextField();
        reglable17 = new javax.swing.JLabel();
        rm = new javax.swing.JRadioButton();
        rf = new javax.swing.JRadioButton();
        reglable18 = new javax.swing.JLabel();
        dept = new javax.swing.JTextField();
        removeStudent = new javax.swing.JPanel();
        outId2 = new javax.swing.JLabel();
        outId3 = new javax.swing.JLabel();
        rebtn = new javax.swing.JButton();
        relname = new javax.swing.JTextField();
        reserial = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        reid = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        headPanel.setBackground(new java.awt.Color(51, 51, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/natnael/Pictures/aastulogo.jpg")); // NOI18N

        HeadLable.setBackground(new java.awt.Color(51, 51, 0));
        HeadLable.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        HeadLable.setForeground(new java.awt.Color(51, 51, 255));
        HeadLable.setText("AASTU PC REGISTRATION SYSTEM");
        HeadLable.setOpaque(true);

        jLabel4.setForeground(new java.awt.Color(255, 255, 204));
        jLabel4.setText("LOGED IN AS ");

        btnlogout.setBackground(new java.awt.Color(0, 0, 0));
        btnlogout.setForeground(new java.awt.Color(255, 255, 255));
        btnlogout.setText("LOGOUT");
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout headPanelLayout = new javax.swing.GroupLayout(headPanel);
        headPanel.setLayout(headPanelLayout);
        headPanelLayout.setHorizontalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(HeadLable, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlogout))
                .addContainerGap())
        );
        headPanelLayout.setVerticalGroup(
            headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headPanelLayout.createSequentialGroup()
                .addGroup(headPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(headPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnlogout)
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(headPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(HeadLable)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        navPanel.setBackground(new java.awt.Color(0, 51, 51));

        btnin.setBackground(new java.awt.Color(139, 139, 25));
        btnin.setText("CHECK_IN");
        btnin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninActionPerformed(evt);
            }
        });

        btnout.setBackground(new java.awt.Color(139, 139, 25));
        btnout.setText("CHECK_OUT");
        btnout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnoutActionPerformed(evt);
            }
        });

        btnreg.setBackground(new java.awt.Color(139, 139, 25));
        btnreg.setForeground(new java.awt.Color(0, 0, 0));
        btnreg.setText("REGISTER");
        btnreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(139, 139, 25));
        jButton1.setText("REMOVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navPanelLayout = new javax.swing.GroupLayout(navPanel);
        navPanel.setLayout(navPanelLayout);
        navPanelLayout.setHorizontalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnreg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        navPanelLayout.setVerticalGroup(
            navPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navPanelLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btnin)
                .addGap(79, 79, 79)
                .addComponent(btnout)
                .addGap(85, 85, 85)
                .addComponent(btnreg)
                .addGap(81, 81, 81)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        formPanel.setBackground(new java.awt.Color(255, 0, 0));
        formPanel.setLayout(new java.awt.CardLayout());

        welcomePanel.setBackground(new java.awt.Color(255, 204, 204));
        welcomePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        jLabel8.setFont(new java.awt.Font("DialogInput", 1, 24)); // NOI18N
        jLabel8.setText("WELCOME TO AASTU PC REGSTRATION SYSTEM SECURITY ");

        javax.swing.GroupLayout welcomePanelLayout = new javax.swing.GroupLayout(welcomePanel);
        welcomePanel.setLayout(welcomePanelLayout);
        welcomePanelLayout.setHorizontalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(794, Short.MAX_VALUE))
        );
        welcomePanelLayout.setVerticalGroup(
            welcomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(welcomePanelLayout.createSequentialGroup()
                .addGap(199, 199, 199)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1190, Short.MAX_VALUE))
        );

        formPanel.add(welcomePanel, "card2");

        checkinPanel.setBackground(new java.awt.Color(81, 25, 70));
        checkinPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        inLable1.setForeground(new java.awt.Color(255, 255, 255));
        inLable1.setText("STUD_ID");

        inLabel2.setForeground(new java.awt.Color(255, 255, 255));
        inLabel2.setText("SERIAL_NO");

        inIdp.setBackground(new java.awt.Color(255, 255, 179));
        inIdp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inIdpActionPerformed(evt);
            }
        });

        inSer.setBackground(new java.awt.Color(255, 255, 179));

        chek_IN.setText("CHECK_IN");
        chek_IN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chek_INActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LAST NAME");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText(" FIRST NAME");

        firtName.setBackground(new java.awt.Color(255, 255, 179));
        firtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firtNameActionPerformed(evt);
            }
        });

        lastName.setBackground(new java.awt.Color(255, 255, 179));
        lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(51, 255, 51));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CHEK IN FORM");

        javax.swing.GroupLayout checkinPanelLayout = new javax.swing.GroupLayout(checkinPanel);
        checkinPanel.setLayout(checkinPanelLayout);
        checkinPanelLayout.setHorizontalGroup(
            checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinPanelLayout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, checkinPanelLayout.createSequentialGroup()
                        .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inLable1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chek_IN, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lastName)
                                .addComponent(inIdp)
                                .addComponent(inSer)
                                .addComponent(firtName, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(1089, Short.MAX_VALUE))
        );
        checkinPanelLayout.setVerticalGroup(
            checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkinPanelLayout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firtName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inIdp, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inLable1))
                .addGap(21, 21, 21)
                .addGroup(checkinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inSer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inLabel2))
                .addGap(62, 62, 62)
                .addComponent(chek_IN)
                .addContainerGap(1026, Short.MAX_VALUE))
        );

        formPanel.add(checkinPanel, "card2");

        checkoutPanel.setBackground(new java.awt.Color(153, 255, 204));
        checkoutPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        checkoutPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        outId.setText("STUDENT_ID");
        checkoutPanel.add(outId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 103, 33));

        outId1.setText("SERIAL_NO");
        checkoutPanel.add(outId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 103, 30));

        checkout.setText("CHECK_OUT");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });
        checkoutPanel.add(checkout, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 144, -1));

        outtext2.setBackground(new java.awt.Color(255, 255, 179));
        outtext2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outtext2ActionPerformed(evt);
            }
        });
        checkoutPanel.add(outtext2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 219, 33));

        outserial.setBackground(new java.awt.Color(255, 255, 179));
        checkoutPanel.add(outserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 219, 30));

        outtext1.setBackground(new java.awt.Color(255, 255, 179));
        outtext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outtext1ActionPerformed(evt);
            }
        });
        checkoutPanel.add(outtext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 219, 33));

        outid.setBackground(new java.awt.Color(255, 255, 179));
        outid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outidActionPerformed(evt);
            }
        });
        checkoutPanel.add(outid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 219, 33));

        jLabel6.setText("LAST NAME");
        checkoutPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, 25));

        jLabel7.setText("FIRST NAME");
        checkoutPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("CHECK OUT FORM");
        checkoutPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 295, 35));

        formPanel.add(checkoutPanel, "card2");

        rgisterPane1.setBackground(new java.awt.Color(51, 51, 255));
        rgisterPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));

        reglable10.setForeground(new java.awt.Color(255, 255, 255));
        reglable10.setText("FIRST NAME");

        reglable11.setForeground(new java.awt.Color(255, 255, 255));
        reglable11.setText("LAST NAME");

        reglable12.setForeground(new java.awt.Color(255, 255, 255));
        reglable12.setText("STUDENT ID");

        reglable13.setForeground(new java.awt.Color(255, 255, 255));
        reglable13.setText("PC PRAND");

        reglable14.setForeground(new java.awt.Color(255, 255, 255));
        reglable14.setText("SERIAL NUMBER");

        reglable15.setForeground(new java.awt.Color(255, 255, 255));
        reglable15.setText("BLOCK NUMBER");

        reglable16.setForeground(new java.awt.Color(255, 255, 255));
        reglable16.setText("DORM NUMBER");

        fnt.setBackground(new java.awt.Color(255, 255, 179));
        fnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fntActionPerformed(evt);
            }
        });

        lnt.setBackground(new java.awt.Color(255, 255, 179));
        lnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lntActionPerformed(evt);
            }
        });

        idt.setBackground(new java.awt.Color(255, 255, 179));
        idt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtActionPerformed(evt);
            }
        });

        brandt.setBackground(new java.awt.Color(255, 255, 179));
        brandt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandtActionPerformed(evt);
            }
        });

        serialt.setBackground(new java.awt.Color(255, 255, 179));
        serialt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialtActionPerformed(evt);
            }
        });

        blockt.setBackground(new java.awt.Color(255, 255, 179));
        blockt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blocktActionPerformed(evt);
            }
        });

        dormt.setBackground(new java.awt.Color(255, 255, 179));
        dormt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dormtActionPerformed(evt);
            }
        });

        regbtn.setText("REGISTER");
        regbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regbtnActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 153, 153));
        jLabel5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 153, 153));
        jLabel5.setText("                  REGISTRITION FORM");

        reglabel9.setForeground(new java.awt.Color(255, 255, 255));
        reglabel9.setText("POHNE NUMBER");

        pt.setBackground(new java.awt.Color(255, 255, 179));
        pt.setMaximumSize(new java.awt.Dimension(4, 19));

        reglable17.setForeground(new java.awt.Color(255, 255, 255));
        reglable17.setText("SEX");

        rm.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup1.add(rm);
        rm.setForeground(new java.awt.Color(238, 238, 238));
        rm.setText("Male");
        rm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmActionPerformed(evt);
            }
        });

        rf.setBackground(new java.awt.Color(51, 51, 255));
        buttonGroup1.add(rf);
        rf.setForeground(new java.awt.Color(238, 238, 238));
        rf.setText("Female");
        rf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rfActionPerformed(evt);
            }
        });

        reglable18.setForeground(new java.awt.Color(255, 255, 255));
        reglable18.setText("DEPARTEMENT");

        dept.setBackground(new java.awt.Color(255, 255, 179));
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rgisterPane1Layout = new javax.swing.GroupLayout(rgisterPane1);
        rgisterPane1.setLayout(rgisterPane1Layout);
        rgisterPane1Layout.setHorizontalGroup(
            rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rgisterPane1Layout.createSequentialGroup()
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rgisterPane1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rgisterPane1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(reglable10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reglable11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reglable12, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reglable17, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reglable13, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reglable14)
                            .addComponent(reglable18)
                            .addComponent(reglable15)
                            .addComponent(reglable16, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reglabel9))
                        .addGap(46, 46, 46)
                        .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(serialt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(brandt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lnt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fnt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rgisterPane1Layout.createSequentialGroup()
                                .addComponent(rm, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(rf, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(blockt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dormt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(regbtn)
                                .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(42, 42, 42))
        );
        rgisterPane1Layout.setVerticalGroup(
            rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rgisterPane1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reglable10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reglable11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reglable12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reglable17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rm)
                    .addComponent(rf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reglable13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(serialt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reglable14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dept, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reglable18, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reglable15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blockt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reglable16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dormt, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(rgisterPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reglabel9)
                    .addComponent(pt, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(regbtn)
                .addContainerGap())
        );

        formPanel.add(rgisterPane1, "card5");

        removeStudent.setBackground(new java.awt.Color(153, 153, 255));
        removeStudent.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        removeStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        outId2.setText("STUDENT_ID");
        removeStudent.add(outId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 103, 33));

        outId3.setText("SERIAL_NO");
        removeStudent.add(outId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 103, 30));

        rebtn.setText("REMOVE");
        rebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rebtnActionPerformed(evt);
            }
        });
        removeStudent.add(rebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, 144, -1));

        relname.setBackground(new java.awt.Color(255, 255, 179));
        relname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                relnameActionPerformed(evt);
            }
        });
        removeStudent.add(relname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 219, 33));

        reserial.setBackground(new java.awt.Color(255, 255, 179));
        removeStudent.add(reserial, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, 219, 30));

        fname.setBackground(new java.awt.Color(255, 255, 179));
        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });
        removeStudent.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 219, 33));

        reid.setBackground(new java.awt.Color(255, 255, 179));
        reid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reidActionPerformed(evt);
            }
        });
        removeStudent.add(reid, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 219, 33));

        jLabel11.setText("LAST NAME");
        removeStudent.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, 25));

        jLabel12.setText("FIRST NAME");
        removeStudent.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("REMOVE STUDENT FORM");
        removeStudent.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, 295, 35));

        formPanel.add(removeStudent, "card2");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(navPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(headPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(navPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(formPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninActionPerformed
        // TODO add your handling code here:
        formPanel.removeAll();
        formPanel.repaint();
        formPanel.revalidate();

        formPanel.add(checkinPanel);
        formPanel.repaint();
        formPanel.revalidate();
    }//GEN-LAST:event_btninActionPerformed

    private void btnoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnoutActionPerformed
        // TODO add your handling code here:
        formPanel.removeAll();
        formPanel.repaint();
        formPanel.revalidate();

        formPanel.add(checkoutPanel);
        formPanel.repaint();
        formPanel.revalidate();
    }//GEN-LAST:event_btnoutActionPerformed

    private void btnregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregActionPerformed
        // TODO add your handling code here:
        formPanel.removeAll();
        formPanel.repaint();
        formPanel.revalidate();

        formPanel.add(rgisterPane1);
        formPanel.repaint();
        formPanel.revalidate();
    }//GEN-LAST:event_btnregActionPerformed

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        // TODO add your handling code here:
        login lg = new login();
        lg.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void outtext2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outtext2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outtext2ActionPerformed

    private void chek_INActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chek_INActionPerformed
        // TODO add your handling code here:
        
        String name = firtName.getText();
        String lname = lastName.getText();
        String id = inIdp.getText();
        String serial = inSer.getText();
        String query = "select * from computers";
        jdbc db = new jdbc();
       boolean check2 = false;
        try {
            ResultSet rs1 = db.s1.executeQuery(query);
            while(rs1.next()){
                
                if(id.equals(rs1.getString(1))){
                    check2 = true;
                    if(serial.equals((rs1.getString(9)))){
                        if(rs1.getInt(11) != 1){
                            
                            JOptionPane.showMessageDialog(null,"wecome "+rs1.getString(2) + " " + rs1.getString(3));
                  
                                        String fname = rs1.getString(1);
                                        String llname = rs1.getString(2);
                                        String Id = rs1.getString(3);
                                        String Sex= rs1.getString(4);
                                        int block_no = rs1.getInt(5);
                                        int room_no = rs1.getInt(6);
                                        String deba = rs1.getString(7);
                                         String pc_brand = rs1.getString(8);
                                         String serial_no = rs1.getString(9);
                                          String phone = rs1.getString(10);
                                           String status = "in";
                                            try{
                                                  File file = new File("history.txt");
                                                    PrintWriter output = new PrintWriter(new BufferedWriter(new FileWriter(file,true)));
                                                    output.print(fname+" ");
                                                    output.print(llname+" ");
                                                    output.print(Id+" ");
                                                    output.print(Sex+" ");
                                                    output.print(block_no+" ");
                                                    output.print(room_no+" ");
                                                    output.print(deba+" ");
                                                    output.print(pc_brand+" ");
                                                    output.print(serial_no+" ");
                                                    output.print(phone+" ");
                                                    output.println(status+" ");
                                                    output.close();
                                         }catch(Exception e){
                                             System.out.println(e);
                                         }
                                            String qury4 = "update computers set status = 1 where id ='"+id+"'";
                                         db.s1.executeUpdate(qury4);
                                    
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"This is pc status is check in he/she can't Enter");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"serial number does match he/she can't Enter");
                    }   
             }
              
                
            }
            if(!check2){
                JOptionPane.showMessageDialog(null,"student id does not exists");
            }
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearCheckIn();
        
    }//GEN-LAST:event_chek_INActionPerformed

    private void inIdpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inIdpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inIdpActionPerformed

    private void fntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fntActionPerformed

    private void lntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lntActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lntActionPerformed

    private void idtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idtActionPerformed

    private void brandtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandtActionPerformed

    private void serialtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialtActionPerformed

    private void blocktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blocktActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blocktActionPerformed

    private void dormtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dormtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dormtActionPerformed

    private void regbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regbtnActionPerformed
        // TODO add your handling code here:
        if(!(fnt.getText().toString()).isEmpty()){
            if(!(lnt.getText().toString()).isEmpty()){
                if(!(idt.getText().toString()).isEmpty()){
                    if(rm.isSelected() || rf.isSelected()){
                        if(!(brandt.getText().toString()).isEmpty()){
                            if(!(serialt.getText().toString()).isEmpty()){
                                if(!(dept.getText().toString()).isEmpty()){
                                    if(!(blockt.getText().toString()).isEmpty()){
                                        if(!(dormt.getText().toString()).isEmpty()){
                                            if(!(pt.getText().toString()).isEmpty()){
                                                register();
                                            }
                                            else{
                                                JOptionPane.showMessageDialog(null,"Please Enter Phone Number");
                                            }
                                        }
                                        else{
                                            JOptionPane.showMessageDialog(null,"Please Enter Dorm Number");
                                        }
                                    }
                                    else{
                                        JOptionPane.showMessageDialog(null,"Please Enter Block Number");
                                    }

                                }
                                else{
                                    JOptionPane.showMessageDialog(null,"Please Enter Departement");
                                }
                            }
                            else{
                                JOptionPane.showMessageDialog(null,"Please Serial Number");
                            }
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"Please Enter Pc Brand");
                        }
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Please Select Sex");
                    }
                }
                else{
                    JOptionPane.showMessageDialog(null,"Please Enter Student Id");
                }
            }
            else{
                JOptionPane.showMessageDialog(null,"Please Enter Last name ");
            }
        }
        else{
            JOptionPane.showMessageDialog(null,"Please Enter First name ");
        }

    }//GEN-LAST:event_regbtnActionPerformed

    private void rmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmActionPerformed

    }//GEN-LAST:event_rmActionPerformed

    private void rfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rfActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptActionPerformed

    private void lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameActionPerformed

    private void firtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firtNameActionPerformed

    private void outtext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outtext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outtext1ActionPerformed

    private void outidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outidActionPerformed

    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // TODO add your handling code here:
               
        String oname = outtext1.getText();
        String olname = outtext2.getText();
        String oid = outid.getText();
        String oserial = outserial.getText();
        String query = "select * from computers";
        jdbc db = new jdbc();
        boolean check = false;
       
        try {
            ResultSet rs1 = db.s1.executeQuery(query);
            while(rs1.next()){
                if(oid.equals(rs1.getString(1))){
                    check = true;
                    if(oserial.equals((rs1.getString(9)))){
                        if(rs1.getInt(11) != 0){
                            
                            
                            JOptionPane.showMessageDialog(null,"have nice time "+rs1.getString(2) + " " + rs1.getString(3));
                         
                                        String ofname = rs1.getString(1);
                                        String ollname = rs1.getString(2);
                                        String oId = rs1.getString(3);
                                        String oSex= rs1.getString(4);
                                        int oblock_no = rs1.getInt(5);
                                        int oroom_no = rs1.getInt(6);
                                        String odeba = rs1.getString(7);
                                        String opc_brand = rs1.getString(8);
                                        String oserial_no = rs1.getString(9);
                                        String ophone = rs1.getString(10);
                                        String ostatus = "out";
                                         try{
                                                  File file = new File("history.txt");
                                                    PrintWriter output = new PrintWriter(new BufferedWriter(new FileWriter(file,true)));
                                                    output.print(ofname+" ");
                                                    output.print(ollname+" ");
                                                    output.print(oId+" ");
                                                    output.print(oSex+" ");
                                                    output.print(oblock_no+" ");
                                                    output.print(oroom_no+" ");
                                                    output.print(odeba+" ");
                                                    output.print(opc_brand+" ");
                                                    output.print(oserial_no+" ");
                                                    output.print(ophone+" ");
                                                    output.println(ostatus+" ");
                                                    output.close();
                                         }catch(Exception e){
                                             System.out.println(e);
                                         }
                                         
                                         String qury4 = "update computers set status = 0 where id ='"+oid+"'";
                                         db.s1.executeUpdate(qury4);
                                    
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"This is pc status is check out he/she can't leave");
                        }
                    }
                    else{
                         int a = JOptionPane.showConfirmDialog(this,"serial number does not  match he/she can't leave. do you want to send alert to admin ","ERROR",JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
                       if(a==0){
                         String alert="";
                        alert  += oname+"#"+olname+"#"+oid+"#"+oserial;
                        Client client = new Client(alert);  
                       }   
                    }   
             }
     
            }
            if(!check){
                JOptionPane.showMessageDialog(null,"student id does not exists");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(main.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        clearCheckout();
    }//GEN-LAST:event_checkoutActionPerformed

    private void rebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rebtnActionPerformed
        // TODO add your handling code here:
          jdbc dbc  = new jdbc();
        String rfname,rename,red,resrial;
        
        rfname=fname.getText();
        rename=relname.getText();
        red=reid.getText();
        resrial=reserial.getText();
         try{
              int a = JOptionPane.showConfirmDialog(this,"DO YOU REAL WANT TO DELETE THE STUDENT","CONFORMATION",JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE);
                       if(a==0){
                           String qury = "delete from computers where id = '"+ red +"'";
                           dbc.s1.executeUpdate(qury);
                           JOptionPane.showMessageDialog(null,"Sucessfully deleted" +rfname);
                       }
         
            
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(null,"not deleted");
       }

    
    }//GEN-LAST:event_rebtnActionPerformed

    private void relnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_relnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_relnameActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void reidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reidActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        formPanel.removeAll();
        formPanel.repaint();
        formPanel.revalidate();

        formPanel.add(removeStudent);
        formPanel.repaint();
        formPanel.revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    void register(){
        jdbc dbc = new jdbc();
        String fn,ln,id,dep,phone,serial,brand,sex="other"; 
       
        id = idt.getText().toString();
        fn = fnt.getText().toString();
        ln = lnt.getText().toString();
        if(rm.isSelected()){
       sex = "Male";
         }
        else if(rf.isSelected()){
       sex = "Female";
        }
        dep = dept.getText();
        phone = pt.getText();
        int dorm = Integer.parseInt(dormt.getText());
        int block = Integer.parseInt(blockt.getText());
        serial = serialt.getText();
        brand = brandt.getText();
       try{
           String qr ="insert into computers values('"+id+"','"+fn+"','"+ln+"','"+sex+"',"+block+","+dorm+",'"+dep+"','"+brand+"','"+serial+"','"+phone+"')";
           dbc.s1.executeUpdate(qr);
         
            JOptionPane.showMessageDialog(null,"Sucessfully Regesterd");
            clearRegister();
       }
       catch(Exception e){
            JOptionPane.showMessageDialog(null,"A student With the same id Exists\nPlease insert another id");
       }
    }
    
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HeadLable;
    private javax.swing.JTextField blockt;
    private javax.swing.JTextField brandt;
    private javax.swing.JButton btnin;
    private javax.swing.JButton btnlogout;
    private javax.swing.JButton btnout;
    private javax.swing.JButton btnreg;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel checkinPanel;
    private javax.swing.JButton checkout;
    private javax.swing.JPanel checkoutPanel;
    private javax.swing.JButton chek_IN;
    private javax.swing.JTextField dept;
    private javax.swing.JTextField dormt;
    private javax.swing.JTextField firtName;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fnt;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel headPanel;
    private javax.swing.JTextField idt;
    private javax.swing.JTextField inIdp;
    private javax.swing.JLabel inLabel2;
    private javax.swing.JLabel inLable1;
    private javax.swing.JTextField inSer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField lnt;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navPanel;
    private javax.swing.JLabel outId;
    private javax.swing.JLabel outId1;
    private javax.swing.JLabel outId2;
    private javax.swing.JLabel outId3;
    private javax.swing.JTextField outid;
    private javax.swing.JTextField outserial;
    private javax.swing.JTextField outtext1;
    private javax.swing.JTextField outtext2;
    private javax.swing.JTextField pt;
    private javax.swing.JButton rebtn;
    private javax.swing.JButton regbtn;
    private javax.swing.JLabel reglabel9;
    private javax.swing.JLabel reglable10;
    private javax.swing.JLabel reglable11;
    private javax.swing.JLabel reglable12;
    private javax.swing.JLabel reglable13;
    private javax.swing.JLabel reglable14;
    private javax.swing.JLabel reglable15;
    private javax.swing.JLabel reglable16;
    private javax.swing.JLabel reglable17;
    private javax.swing.JLabel reglable18;
    private javax.swing.JTextField reid;
    private javax.swing.JTextField relname;
    private javax.swing.JPanel removeStudent;
    private javax.swing.JTextField reserial;
    private javax.swing.JRadioButton rf;
    private javax.swing.JPanel rgisterPane1;
    private javax.swing.JRadioButton rm;
    private javax.swing.JTextField serialt;
    private javax.swing.JPanel welcomePanel;
    // End of variables declaration//GEN-END:variables

    private void clearRegister() {
        lnt.setText("");
        fnt.setText("");
        idt.setText("");
        brandt.setText("");
        dormt.setText("");
        blockt.setText("");
        dept.setText("");
        pt.setText("");
        serialt.setText("");
    }

    private void clearCheckIn() {
    inIdp.setText("");
    inSer.setText("");
    firtName.setText("");
    lastName.setText("");
    }

    private void clearCheckout() {
    outtext1.setText("");
    outtext2.setText("");
    outid.setText("");
    outserial.setText("");
    }

}
